### ISSUE TITLE
facing issue while running ProjectMain

### ISSUE THREAD

**Issue by Sathiyarajan** [ankit0811/apache-task-to-take#4]
Feb 09, 2022 11:45:45 PM Config <init>
INFO: Reading default config file from resources/config.properties
Feb 09, 2022 11:45:45 PM Config <init>
INFO: Reading default config file from resources/config.properties
Feb 09, 2022 11:45:50 PM ExtractGitHubIssues getConnectionInputStream
INFO: con.getHeaderFields().get("X-RateLimit-Remaining") = [57]
Feb 09, 2022 11:45:50 PM ExtractGitHubIssues setEndPageNumber
INFO: End page number is : 24
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "allow_forking" (class Entities.Repository), not marked as ignorable (74 known properties: "branches_url", "size", "git_url", "private", "permissions", "has_downloads", "watchers_count", "stargazers_url", "name", "clone_url", "compare_url", "git_tags_url", "notifications_url", "id", "open_issues_count", "forks_url", "keys_url", "blobs_url", "contributors_url", "issue_comment_url", "labels_url", "owner", "assignees_url", "has_wiki", "updated_at", "ssh_url", "full_name", "git_refs_url", "forks_count", "fork", "trees_url", "events_url", "contents_url", "languages_url", "commits_url", "subscription_url", "open_issues", "statuses_url", "language", "html_url", "collaborators_url", "git_commits_url", "hooks_url", "archived", "teams_url", "stargazers_count", "issues_url", "merges_url", "homepage", "url", "forks", "archive_url", "node_id", "pushed_at", "description", "pulls_url", "has_issues", "downloads_url", "comments_url", "milestones_url", "watchers", "subscribers_url", "license", "tags_url", "has_pages", "default_branch", "created_at", "issue_events_url", "releases_url" [truncated]])
 at [Source: (sun.net.www.protocol.http.HttpURLConnection$HttpInputStream); line: 1, column: 6124] (through reference chain: java.lang.Object[][0]->Entities.Repository["allow_forking"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:840)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1206)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1592)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1570)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:195)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:21)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3242)
	at ExtractGitHubIssues.setRepositories(ExtractGitHubIssues.java:98)
	at ProjectMain.main(ProjectMain.java:59)

**Comment by Sathiyarajan** [comment]
resolving the above issue by adding the POJOs for the latest git api. will make a PR in later this week after complete testing.

https://api.github.com/orgs/apache/repos?per_page=100

@ankit0811
